### ISSUE TITLE
Fix notify.send 

### ISSUE THREAD

**Issue by Trafitto** [Trafitto/PosteItaliane-Home-Auctions-Notify#1]
Currently the email notification function does not work

It needs to work with the most common providers: Gmail (which requires user confirmation) Outlook and Hotmail

**Comment by capitanfindusfi** [comment]
having a look at it 👀

**Comment by capitanfindusfi** [comment]
Can be referenced [from this](https://github.com/Trafitto/PosteItaliane-Home-Auctions-Notify/pull/3)
