### ISSUE TITLE
Email provider taken from env

### ISSUE THREAD

**Issue by Trafitto** [Trafitto/PosteItaliane-Home-Auctions-Notify#2]
The email provider must be passed via an environment variable

**Comment by capitanfindusfi** [comment]
I'm taking care of this 👀

**Comment by capitanfindusfi** [comment]
Can be referenced [from this](https://github.com/Trafitto/PosteItaliane-Home-Auctions-Notify/pull/3)

**Comment by Trafitto** [comment]
Thanks for your hard work.
